config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  get "products/new"
  get "products/create"
  get "products/edit"
  get "products/update"
  get "products/destroy"
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get 'customers/edit_customer', to: 'customers#edit_customer', as: 'edit_customer'
  post 'customers/manage_customer', to: 'customers#manage_customer', as: 'manage_customer'

  get "roles/:id/permissions", to: "roles#permissions", as: "permissions"
  post "roles/:id/store_permissions", to: "roles#store_permissions", as: "store_permissions"

  resources :roles
  resources :staff_users
  resources :customers, only: [:edit, :update]
  resources :dashboard, only: [:index]
  resources :products
  root "dashboard#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container d-flex gap-2">

<% if admin_signed_in? && current_admin.super_admin? %>
	<%= link_to "Roles", roles_path, class: 'btn btn-primary mt-4' %>
  <%= link_to "Staff Users", staff_users_path, class: 'btn btn-primary ml-4 mt-4' %>
<% end %>

<% if admin_signed_in? && current_admin.staff_user? %>
 <%= link_to "Products", products_path, class: 'btn btn-primary ml-4 mt-4' %>
<% end %>

<% if admin_signed_in? && !current_admin.super_admin? %>
	    <%= link_to "Update Password", edit_admin_registration_path, class: 'btn btn-primary ml-4 mt-4' %>
	    <%= button_to "Delete Account", admin_registration_path, method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-primary ml-4 mt-4' %>
      <%= link_to "Update Profile", edit_customer_path, class: 'btn btn-primary ml-4 mt-4' %>
<% end %>

</div>