config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  get "products/new"
  get "products/create"
  get "products/edit"
  get "products/update"
  get "products/destroy"
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get 'customers/edit_customer', to: 'customers#edit_customer', as: 'edit_customer'
  post 'customers/manage_customer', to: 'customers#manage_customer', as: 'manage_customer'

  get "roles/:id/permissions", to: "roles#permissions", as: "permissions"
  post "roles/:id/store_permissions", to: "roles#store_permissions", as: "store_permissions"

  resources :roles
  resources :staff_users
  resources :customers, only: [:edit, :update]
  resources :dashboard, only: [:index]
  resources :products
  root "dashboard#index"

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :admins
  has_many :permission_roles, dependent: :destroy
  has_many :permissions, through: :permission_roles
  validates :name, presence: true, uniqueness: true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_role, only: [:edit, :update, :destroy, :permissions, :store_permissions]
  before_action :fetch_permissions, only: [:permissions]
  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end


  def create
    @role = Role.new(role_params)
    if @role.save
      flash[:notice] = 'Role created successfully'
      redirect_to roles_path
    else
      flash[:notice] = @role.errors.full_messages.join(",")
      redirect_to new_role_path
    end
  end

  def edit
  end

  def update
		if(@role.update(role_params))
			flash[:notice] = 'Role updated successfully'
			redirect_to roles_path
		else
			flash[:notice] = @role.errors.full_messages.join(",")
			redirect_to role_path(@role)
		end
	end

  def destroy
    if @role.destroy
      flash[:notice] = 'Role deleted successfully'
    else
      flash[:notice] = @role.errors.full_messages.join(",")
    end
    redirect_to roles_path
  end

  def permissions
		@select_permission_ids = @role.permissions.ids
	end

  def store_permissions
		@role.permission_ids = params[:permission_ids]
		flash[:notice] = 'Permissions were assigned successfully!'
		redirect_to roles_path
	end


  def fetch_permissions
		@permissions = Permission.all
	end

  def find_role
    @role = Role.find_by id: params[:id]
    unless @role
      flash[:notice] = "Role not found!!!"
      redirect_to roles_path
    end

  def role_params
    params.require(:role).permit(:name)
  end
end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for @role do |f| %>
	<div class="mb-2">
        <span>Role Name: </span>
        <%= f.text_field :name, required: true %>
    </div>

    <div class="mb-2">
        <%= f.submit 'Create Role' %>
    </div>
<% end %>
<div class="mb-2">
    <%= link_to 'Back to Role list', roles_path %>
</div>

app/views/roles/edit.html.erb
<div class="container">
    <h5>Edit Role</h5>
	<%= render 'form' %>
</div>

app/views/roles/index.html.erb
<div class="container">
	<h5>Roles List</h5>
	<table class="table table-striped" style="width:70%">
		<thead style="width:70%">
			<tr>
				<th>Role Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<% @roles.each do |role| %>
		<tr>
			<td>
				<%= role.name %>
			</td>			
      <td>
        <%= link_to 'Edit', edit_role_path(role)  %> |
        <%= button_to 'Delete', role_path(role), method: :delete, class: 'btn btn-link p-0 mb-1 text-primary', form: { class: 'd-inline' }  %>  |
				<%= link_to 'Permissions', permissions_path(role)  %>
      </td>
		</tr>
		<% end %>
	</table>	
</div>

<%= link_to 'Create Role', new_role_path %><br/>

app/views/roles/new.html.erb
<div class="container">
    <h5>New Role</h5>
	<%= render 'form' %>
</div>

app/views/roles/permissions.html.erb
<div class="container">
    <h5>Associate Permissions With Role</h5>
	<%= form_for :permission, url: store_permissions_url(@role), method: :post do |f| %>
		<% @permissions.each do |permission| %>
			<div class="mb-2">
<%= check_box_tag 'permission_ids[]', permission.id, 
@select_permission_ids.include?(permission.id), id: "permission_#{permission.id}" %>
		        <label for=<%= "permission_#{permission.id}" %>><%= permission.name %></span>
		    </div>
		<% end %>

	    <div class="mb-2">
	        <%= f.submit 'Associate Permissions' %>
	    </div>
	<% end %>

</div>